[package]
name = "bedrockrs_addon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
uuid = "1.10.0"
once_cell = "1.19.0"